# owserver configuration 

## device(s)
{{- range .devices }}
### {{ .device_type }}
{{- if eq .device_type "fake" }}
server: FAKE = DS18B20
{{- else if and (eq .device_type "usb") .device }}
server: usb = {{ .device }}
{{- else if eq .device_type "usb" }}
server: usb = all
{{- end }}
{{- end }}

!server: server = 4304
server: port = 4304
http: port = 8099

{{ if .temperature_scale }}
## temperature scale
{{ .temperature_scale }}
{{- end }}
